apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-webapp-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/samvarankashyap/argocd-workshop.git
    targetRevision: HEAD
    path: gitops/components/go-webapp/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-go

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
